export type Locale = "zh" | "en";
const en = {
  space: "PERSONAL SPACE",
  edition: "A SMALL, OPEN UNIVERSE",
  title: "Room to unfold.",
  subtitle: "A place for everything that is yet to come.",
  home: "The desktop",
  library: "Library",
  projects: "Playground",
  about: "About this space",
  subscribe: "Letters",
  search: "Find your way",
  searchHint: "Search places, not articles…",
  noResults: "No places found. Try “library” or “letters”.",
  navigationOnly: "Places in this space · content will arrive later",
  preferences: "Make it yours",
  language: "Switch to Chinese",
  soundOn: "Turn sound on",
  soundOff: "Turn sound off",
  guide: "Take a little tour",
  close: "Close",
  back: "Back to the desktop",
  returnToForm: "Start another test",
  serviceChecking: "Checking the local subscription service…",
  retry: "Try the connection again",
  audioUnavailable:
    "Audio is unavailable. Try again after interacting with this page.",
  sceneEyebrow: "THE SPACE BETWEEN",
  sceneTitle: "A little world,\nwaiting to open.",
  sceneAction: "Step inside",
  sceneHint: "Move gently. Watch the water.",
  shelfCaption: "THINGS TO KEEP",
  shelfTitle: "An open shelf.",
  shelfMeta: "Waiting for the first page",
  projectCaption: "THINGS TO MAKE",
  projectTitle: "Ideas need a little room.",
  projectMeta: "No projects here. Yet.",
  aboutCaption: "THE PERSON BEHIND",
  aboutTitle: "Every story\nstarts somewhere.",
  aboutAction: "A blank page, for now",
  newsletterCaption: "LETTERS, OCCASIONALLY",
  newsletterTitle: "Leave a little\nspace in your inbox.",
  newsletterAction: "Open the envelope",
  previewBadge: "Local preview",
  deliveryPending: "Delivery pending",
  atmosphere: "A MOMENT OF QUIET",
  atmosphereTitle: "Soft currents",
  atmosphereHint: "A soundscape, made of waves.",
  timeCaption: "BE HERE, NOW",
  timeZone: "YOUR LOCAL TIME",
  footer: "Made for wandering. Built to grow.",
  footerRight: "Nothing to catch up on.",
  drag: "Move card with pointer or arrow keys",
  emptyTitle: "A little room for what’s next.",
  emptyBody: "The shelves are ready. The stories haven’t arrived yet.",
  emptyProjects: "The workspace is ready for the first idea.",
  emptyAbout: "This page is being kept open for a proper introduction.",
  emptySearch: "No content has been added. You can still explore the space.",
  all: "Everything",
  notes: "Notes",
  reads: "Reading",
  experiments: "Experiments",
  grid: "Grid view",
  list: "List view",
  collectionCount: "0 entries",
  returnHome: "Keep exploring",
  introEyebrow: "BEFORE THE FIRST PAGE",
  introOne: "A small pause.",
  introOneSub: "Outside, the world keeps moving.",
  introTwo: "A place to gather.",
  introTwoSub: "A thought. A spark. A little room to grow.",
  introThree: "Make yourself at home.",
  introThreeSub: "Your next chapter can wait a moment.",
  next: "Continue",
  enter: "Enter the space",
  skip: "Skip introduction",
  replay: "Replay the opening",
  tourOne: "A compass, not a menu.",
  tourOneBody:
    "The navigation icons lead to your library, projects and letters. Hover or focus to see their names.",
  tourTwo: "A desk that moves with you.",
  tourTwoBody:
    "On a computer, enable rearranging in preferences, then move a card by its handle. Your layout stays in this browser.",
  tourThree: "Make a little room.",
  tourThreeBody:
    "Switch language, choose a mood, or open a letter. Everything is here to be explored.",
  tourDone: "I’m ready",
  theme: "Color of the sky",
  day: "Daylight",
  night: "After hours",
  motion: "Movement",
  motionOn: "Full motion",
  motionOff: "Gentle mode",
  motionSystem: "Reduced motion is enabled by your device.",
  rearrange: "Rearrange the desk",
  unlocked: "Unlocked",
  locked: "Locked",
  reset: "Put everything back",
  resetDone: "The desk is back in place.",
  preferencesNote: "Preferences stay in this browser. No account needed.",
  email: "Email address",
  emailPlaceholder: "you@somewhere.com",
  consent: "I agree to receive new-post emails. I can unsubscribe anytime.",
  subscribeSubmit: "Send me a little letter",
  subscribing: "Folding your letter…",
  invalidEmail: "That address doesn’t look quite right.",
  consentError: "Please confirm your email preference first.",
  subscriptionIntro:
    "A quiet note when something new arrives. No content has been published yet.",
  previewNotice:
    "Local test mode. No email will be sent; this browser can preview the confirmation flow.",
  liveUnavailable:
    "Email delivery isn’t connected yet. Your address has not been saved.",
  connectionError: "The connection drifted away. Please try again.",
  rateLimited: "A few too many requests. Please wait a minute.",
  confirmationTitle: "A letter, just for you.",
  confirmationBody:
    "Your request is saved locally as pending. Preview the confirmation below; nothing has been sent to your inbox.",
  confirmButton: "Preview: confirm subscription",
  confirming: "Opening the envelope…",
  confirmedTitle: "You’re on the local list.",
  confirmedBody:
    "Local confirmation complete. No email was sent. Real delivery will be available after a mail service is connected.",
  unsubscribeButton: "Cancel this test subscription",
  unsubscribing: "Updating your preference…",
  unsubscribedTitle: "The page is yours again.",
  unsubscribedBody: "Your local test subscription is cancelled.",
  tokenError: "This confirmation is no longer valid. Please start again.",
  welcomeHint: "Explore with your cursor. Or just take your time.",
  keyboardHint: "Esc to close",
  contentLabel: "Content will come later",
  privacy: "Your address is only used for this subscription flow.",
};
export type Copy = { [K in keyof typeof en]: string };
const zh: Copy = {
  space: "个人空间",
  edition: "一方留给自己的小宇宙",
  title: "慢慢，展开。",
  subtitle: "给还没发生的故事，留一点位置。",
  home: "回到桌面",
  library: "知识书架",
  projects: "灵感工坊",
  about: "关于这里",
  subscribe: "偶尔来信",
  search: "寻找一个入口",
  searchHint: "搜索空间入口，正文还在路上…",
  noResults: "没有找到入口，试试「书架」或「来信」。",
  navigationOnly: "空间导航 · 内容稍后抵达",
  preferences: "布置我的空间",
  language: "Switch to English",
  soundOn: "打开环境音",
  soundOff: "关闭环境音",
  guide: "带我逛一逛",
  close: "关闭",
  back: "回到桌面",
  returnToForm: "重新体验订阅",
  serviceChecking: "正在连接本地订阅服务…",
  retry: "重新连接",
  audioUnavailable: "暂时无法播放声音，请与页面交互后再试一次。",
  sceneEyebrow: "留白之间",
  sceneTitle: "一方小世界，\n等你慢慢展开。",
  sceneAction: "走进这里",
  sceneHint: "轻轻移动，看水面泛起涟漪。",
  shelfCaption: "值得收藏的",
  shelfTitle: "一格空书架。",
  shelfMeta: "等待第一页到来",
  projectCaption: "想要创造的",
  projectTitle: "给想法，一点空间。",
  projectMeta: "第一个项目，还在酝酿",
  aboutCaption: "故事背后的人",
  aboutTitle: "每个故事，\n都有一个起点。",
  aboutAction: "先留一页空白",
  newsletterCaption: "不定期，寄一封信",
  newsletterTitle: "在收件箱里，\n也留一点空白。",
  newsletterAction: "拆开信封",
  previewBadge: "本地预览",
  deliveryPending: "邮件待接入",
  atmosphere: "此刻，安静一点",
  atmosphereTitle: "微澜",
  atmosphereHint: "让声音，像水一样流动。",
  timeCaption: "就在此时",
  timeZone: "你的本地时间",
  footer: "自在漫游，慢慢生长。",
  footerRight: "此刻，不必追赶。",
  drag: "拖动卡片，或用方向键微调",
  emptyTitle: "留一点位置，给接下来的故事。",
  emptyBody: "书架已经备好，故事还没有抵达。",
  emptyProjects: "工坊已经准备好，等待第一个想法。",
  emptyAbout: "这一页，留给未来一次认真的自我介绍。",
  emptySearch: "暂时还没有内容，你可以先逛逛这个空间。",
  all: "全部",
  notes: "笔记",
  reads: "阅读",
  experiments: "实验",
  grid: "卡片视图",
  list: "列表视图",
  collectionCount: "0 条内容",
  returnHome: "继续漫游",
  introEyebrow: "在第一页之前",
  introOne: "先，停一小会。",
  introOneSub: "外面的世界，依然在向前。",
  introTwo: "给思绪一个落点。",
  introTwoSub: "一个念头，一点灵光，一处慢慢生长的地方。",
  introThree: "欢迎，回到自己的节奏。",
  introThreeSub: "下一章的故事，可以再等一会。",
  next: "继续",
  enter: "走进这个空间",
  skip: "跳过开场",
  replay: "重温开场",
  tourOne: "像指南针一样，找到方向。",
  tourOneBody:
    "导航图标通往书架、工坊和来信。悬停或用键盘聚焦，就能看见入口名称。",
  tourTwo: "一张可以重新布置的桌面。",
  tourTwoBody:
    "在电脑上打开设置，开启卡片移动，再拖动手柄调整位置。布局只保存在当前浏览器。",
  tourThree: "用自己的方式，慢慢逛。",
  tourThreeBody:
    "切换语言，换一种天色，或者拆开一封信。这里的每个入口，都可以试一试。",
  tourDone: "开始漫游",
  theme: "天空的颜色",
  day: "日光",
  night: "入夜",
  motion: "动态效果",
  motionOn: "灵动模式",
  motionOff: "轻柔模式",
  motionSystem: "已遵循设备的减少动态效果设置。",
  rearrange: "移动桌面卡片",
  unlocked: "可以移动",
  locked: "已经锁定",
  reset: "恢复原来的位置",
  resetDone: "桌面已经归位。",
  preferencesNote: "偏好只保存在此浏览器，无需账号。",
  email: "电子邮箱",
  emailPlaceholder: "you@somewhere.com",
  consent: "我愿意收到新内容邮件，也可以随时取消订阅。",
  subscribeSubmit: "有新故事时，寄信给我",
  subscribing: "正在折好这封信…",
  invalidEmail: "这个邮箱地址似乎还不完整。",
  consentError: "请先确认你的订阅意愿。",
  subscriptionIntro: "有新的故事时，轻轻提醒你。这里目前还没有发布内容。",
  previewNotice: "本地测试模式：不会发送邮件，可以在此预览确认和取消订阅流程。",
  liveUnavailable: "邮件服务尚未接入，未保存你的邮箱。",
  connectionError: "连接暂时中断了，请再试一次。",
  rateLimited: "操作有些频繁，请稍等一分钟。",
  confirmationTitle: "一封，写给你的信。",
  confirmationBody:
    "订阅请求已在本地保存为待确认。你可以预览下方确认步骤，收件箱不会收到邮件。",
  confirmButton: "预览：确认订阅",
  confirming: "正在拆开信封…",
  confirmedTitle: "已加入本地订阅名单。",
  confirmedBody: "本地确认完成，未发送邮件。真实邮件通知需要后续接入邮件服务。",
  unsubscribeButton: "取消这次测试订阅",
  unsubscribing: "正在更新你的选择…",
  unsubscribedTitle: "空白，再次交还给你。",
  unsubscribedBody: "这次本地测试订阅已经取消。",
  tokenError: "这次确认已失效，请重新发起订阅。",
  welcomeHint: "跟着光走，或者，就在这里停一会。",
  keyboardHint: "按 Esc 关闭",
  contentLabel: "内容，稍后抵达",
  privacy: "邮箱仅用于本次订阅流程。",
};
export const copy: Record<Locale, Copy> = { zh, en };
export const spaces = [
  "home",
  "library",
  "projects",
  "about",
  "subscribe",
] as const;
export type Space = (typeof spaces)[number];
export type Panel =
  | Exclude<Space, "home">
  | "search"
  | "preferences"
  | "guide"
  | null;
export function readSpace(search: string): Panel {
  const value = new URLSearchParams(search).get("space");
  return value &&
    [...spaces.slice(1), "search", "preferences", "guide"].includes(value)
    ? (value as Panel)
    : null;
}
